### ISSUE TITLE
配置目录问题

### ISSUE THREAD

**Issue by Teddy-Zhu** [xuxueli/xxl-mq#3]
```java
/**
	 * zk config file
	 */
	private static final String ZK_ADDRESS_FILE = "/data/webapps/xxl-conf.properties";
```
配置地址可否开放出来,可以自定义

**Comment by xuxueli** [comment]
这个可以后续优化。 “com.xxl.mq.client.rpc.util.Environment” 中ZK地址解析目前只会读取硬盘ZK配置，后续会调整为优先读取项目resource目录ZK配置，硬盘地址作为failover备选方案；

**Comment by Teddy-Zhu** [comment]
@xuxueli thx , 好的
