### ISSUE TITLE
为什么基于zk来进行广播呢？

### ISSUE THREAD

**Issue by jiangxinlingdu** [xuxueli/xxl-mq#5]
基于zk广播的确简单也容易理解，它的qps大吗？  性能应该不太好吧 ，为什么不在有多个client，让那个server发送client呢 接受到数据处理呢？？？？

**Comment by xuxueli** [comment]
你好，ZK性能很强悍的！
部署最简单的一个zk集群，NODE小数量量情况下，TPS可以达到1w+。
可以参考这篇文章 （https://my.oschina.net/xuxueli/blog/750196 ），文章中应用了阿里中间件团队的一个测试结果数据。

**Comment by lirenzuo** [comment]
好的，请问下你现在的这个消息中间件tps是多少呢？  想多了解看看是否合适？

**Comment by xuxueli** [comment]
在mac（i7、16G）上做过一个测试，producer达到5000~6000/s。consumer因为受制于业务逻辑没有测试意义啊。

**Comment by lirenzuo** [comment]
谢谢

**Comment by xuxueli** [comment]
你好，项目正在进行重大重构，新版消息处理逻辑将会收归统一，不再依赖ZK广播，各种消息模型走统一的处理逻辑。
新版将于近期发布！
