### ISSUE TITLE
单机部署可以运行，多网卡多机部署失败

### ISSUE THREAD

**Issue by jlzq1314** [xuxueli/xxl-mq#6]
多机多网卡部署，Brocker提示注册成功
“>>>>>>>>>>> xxl-rpc registe service item, ...........”
但Service端提示：
“>>>>>>>>>>> xxl-rpc，no address from service:........”
跟作者沟通过，怀疑时zk没注册成功。但把它换到同一个环境下也不行，应该是多网卡问题。希望得到解决。

**Comment by xuxueli** [comment]
你好，感谢反馈！
可能因为多网卡注册上了无效IP导致，暂时可以通过修改host指定固定IP方式修复。
后续版本将会支持固定指定IP。如有问题，欢迎加入交流群沟通。

**Comment by xuxueli** [comment]
新版本正在紧急迭代中，机器即将发布。
