### ISSUE TITLE
XxlMqClient 中代码的一个疑问，似乎同步没有起作用

### ISSUE THREAD

**Issue by yyd19921214** [xuxueli/xxl-mq#7]
您好，我在安装并阅读代码时，在xx-mq-client包的XxlMqClient 类中发现getXxlMqService的方法中使用CountDownlatch时，countdown方法在await方法之前，这似乎违背了countDownLatch的使用方法，同步会失效。可以劳烦您解释一下吗？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
此处逻辑作用于断线重连，发生频率较低因此没有太过关注。
这里的CountDownlatch代码可移除，感谢反馈啊。

**Comment by yyd19921214** [comment]
you are so nice!! 以后还请多多指教！我也很想参与到这个project的开发中
