### ISSUE TITLE
XxlMqConsumer的代码似乎有问题

### ISSUE THREAD

**Issue by yyd19921214** [xuxueli/xxl-mq#8]
我在阅读XxlMqConsumer类的代码时，发现如果注入一个TopicComsumer，XxlMqConsumer类在初始化时会watchTopic，但是在initTopicConsumer方法的136行中，似乎执行了ZK注册consumer的逻辑，而且用的是queueConsumerRespository，这里似乎不需要再注册consumer了吧，因为之前已经watchTopic了，即使需要注册，也应该使用topicConsumerRespository吧？
PS：现在代码的逻辑中，key使用的是consumer的topic名称，所以如果在一台机器上，启动两个监听同一Topic的TopicConsumer是不是会有问题？

**Comment by xuxueli** [comment]
你好，感谢关注！
ZK使用Map维护路径的watcher，重复watch只会有一个watcher存在。
上面提到的周期性watch是为了做ZK连接的有效性检测和补偿，非核心代码。
因为ZK连接中断后已经做了重连的逻辑处理。

**Comment by yyd19921214** [comment]
但是在周期性watch的时候应该使用topicConsumerRespository吧？代码里用的是queueConsumerRespository，而这一部分逻辑是在initTopicConsumer里边，具体是在XxlMqConsumer类的136行，您可以看一下

**Comment by xuxueli** [comment]
是的，initTopicConsumer应该只处理topic类型消息的逻辑，已经做了调整并推送master。
赞！欢迎继续PR和ISSUE啊 ：）
