### ISSUE TITLE
关于部署的一个小白问题

### ISSUE THREAD

**Issue by yyd19921214** [xuxueli/xxl-mq#9]
在server端部署时，是不是除了部署xxl-mq-broker这个子项目，还应该部署xxl-mq-client子项目下的broker类，因为只有这样XxlMqBroker才能通过Spring的依赖注入获得xxlMqMessageDao，并且执行init方法?

初次接触分布式CS架构，所以有些细节不是很熟悉，见笑了

**Comment by xuxueli** [comment]
在你需要部署xxl-mq-broker就好了，支持集群部署的。
